[workspace]
resolver = "2"
members = [ "common",
    "day1", "day2", "day3", "day5",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
nom = "7.1.3"
anyhow = "1"
itertools = "0.13"
